// vue/VueDemo/src/App.vue
<template>
    <div>
      <div class="row">
        <div class="col-xs-offset-2 col-xs-8">
          <div class="page-header"><h2>Router Basic - 01</h2></div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-2 col-xs-offset-2">
          <div id="menu" class="list-group">
            <router-link to="/about" class="list-group-item">About</router-link>
            <router-link to="/home" class="list-group-item">Home</router-link>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="panel">
            <div class="panel-body">
              <keep-alive>
                <router-view msg="abc"></router-view>
              </keep-alive>

              <!--<div>
                <h2>about组件</h2>
                <p>接收外部数据：atguigu</p>
                <input type="text">
              </div>-->
            </div>
          </div>
        </div>
      </div>
    </div>
</template>

<script>
  export default {}
</script>

<style>
  #menu .router-link-active{
    color:red;
  }
</style>

// react/react_router/src/components/app.jsx
import React, {Component} from 'react'
import {NavLink, Switch, Route, Redirect} from 'react-router-dom'

import About from '../views/about'
import Home from '../views/home'
import MyNavLink from './MyNavLink'

export default class App extends Component {
    render () {
        return (
            <div>
                <div className="row">
                    <div className="col-xs-offset-2 col-xs-8">
                        <div className="page-header">
                            <h2>React Router Demo</h2>
                        </div>
                    </div>
                </div>

                <div className="row">
                    <div className="col-xs-2 col-xs-offset-2">
                        <div className="list-group">
                            <MyNavLink className="list-group-item" to="/about" >About</MyNavLink>
                            <MyNavLink className="list-group-item" to="/home" >Home</MyNavLink>
                        </div>
                    </div>
                    <div className="col-xs-6">
                        <div className="panel">
                            <div className="panel-body">
                                <Switch>
                                    <Route path="/about" component={About} />
                                    <Route path="/home" component={Home} />
                                    <Redirect to="/about" />
                                </Switch>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}
