// react/react_app/src-users2/components/main.jsx
import React, {Component} from 'react'
import axios from 'axios'
import PubSub from 'pubsub-js'

export default class Main extends Component {

    state = {
        initView: true,
        loading: false,
        users: null,
        errorMsg: null
    }

    componentDidMount () {
        // 订阅消息
        PubSub.subscribe('search', (msg, searchName) => {
            // 更新状态（请求中）
            this.setState({
                initView: false,
                loading: true
            })

            // 发ajax请求
            const url = `https://api.github.com/search/users?q=${searchName}`
            axios.get(url)
                .then(response => {
                    // 得到响应数据
                    const result = response.data
                    const users = result.items.map(item => ({
                        name: item.login,
                        url: item.html_url,
                        avatarUrl: item.avatar_url
                    }))
                    // 更新状态（成功）
                    this.setState({
                        loading: false,
                        users
                    })
                })
                .catch(error => {
                    // 更新状态（失败）
                    this.setState({
                        loading: false,
                        errorMsg: error.message
                    })
                })
        })
    }

    render () {
        const {initView, loading, users, errorMsg} = this.state

        if (initView) {
            return <h2>请输入关键字进行搜索</h2>
        } else if (loading) {
            return <h2>正在请求中...</h2>
        } else if (errorMsg) {
            return <h2>{errorMsg}</h2>
        } else {
            return (
                <div className="row">
                    {
                        users.map((user, index) => (
                            <div className="card" key={index}>
                                <a href={user.url} target="_blank">
                                    <img src={user.avatarUrl} style={{width: '100px'}}/>
                                </a>
                                <p className="card-text">{user.name}</p>
                            </div>
                        ))
                    }
                </div>
            )
        }
    }
}

// vue/vuex_demo/src/components/Main.vue
<template>
  <div>
    <h2 v-if="firstView">输入用户名搜索</h2>
    <h2 v-if="loading">LOADING...</h2>
    <h2 v-if="errorMsg">{{errorMsg}}</h2>
    <div class="row">
      <div class="card" v-for="(user,index) in users" :key="index">
        <a :href="user.url" target="_blank">
          <img :src="user.avatar_url">
        </a>
        <p class="card-text">{{user.name}}</p>
      </div>

    </div>
  </div>
</template>

<script>
    import PubSub from 'pubsub-js'
    import axios from 'axios'

    export default {
      data () {
        return {
          firstView:true,
          loading:false,
          users:null,
          errorMsg:''
        }
      },
      mounted() {
        PubSub.subscribe('search',(msg,searchName) => {
          const url =`https://api.github.com/search/users?q=${searchName}`;
          this.firstView = false;
          this.loading = true;
          this.users = null;
          this.errorMsg = '';
          axios.get(url).then(response => {
            const result = response.data;
            const users = result.items.map(item => ({
              url:item.html_url,
              avatar_url:item.avatar_url,
              name:item.login
            }));

            this.loading = false;
            this.users = users;
          }).catch(error => {
            this.loading = false;
            this.errorMsg = '请求失败';
          })
        })
      }
    }
</script>

<style>
.card {
  float:left;
  width:33.333%;
  padding:.75rem;
  margin-bottom:2rem;
  border:1px solid #efefef;
  text-align:center;
}
  .card img {
    margin-bottom:.75rem;
    border-radius:10px;
    width:80%;
  }
  .card-text {
    font-size:85%;
  }
</style>
