// vue/code/VuexTest/src/App.vue
<template>
  <div>
    <p>click1111 {{count}} times,count is {{evenOrOdd}}</p>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementIfOdd">increment if odd</button>
    <button @click="incrementAsync">increment async</button>
  </div>
</template>

<script>
  export default {
      data () {
          return {
              count:0
          }
      },
      computed: {
          evenOrOdd () {
            return this.count%2===0?"偶数":"奇数"
          }
      },
      methods: {
          increment () {
              const count = this.count;
              this.count = count + 1;
          },
          decrement () {
              const count = this.count;
              this.count = count - 1;
          },
          incrementIfOdd () {
              const count = this.count;
              if(count%2===1){
                  this.count = count + 1;
              }
          },
          incrementAsync () {
              setTimeout(()=>{
                  const count = this.count;
                  this.count = count + 1;
              },1000)
          }
      }
  }
</script>

<style>

</style>

// react/react_redux/src-counter2_redux/components/app.jsx
import React, {Component} from 'react'
import * as actions from '../redux/actions'

export default class App extends Component {

    increment = () => {
        const number = this.select.value*1
        // 调用store的方法更新状态
        this.props.store.dispatch(actions.increment(number))
    }

    decrement = () => {
        const number = this.select.value*1
        // 调用store的方法更新状态
        this.props.store.dispatch(actions.decrement(number))
    }

    incrementIfOdd = () => {
        const number = this.select.value*1
        const count = this.props.store.getState()

        if (count%2 === 1) {
            this.props.store.dispatch(actions.increment(number))
        }
    }

    incrementAsync = () => {
        const number = this.select.value*1
        setTimeout(() => {
            this.props.store.dispatch(actions.increment(number))
        }, 1000)
    }

    render () {
        const count = this.props.store.getState()
        return (
            <div>
                <p>click {count} times</p>
                <div>
                    <select ref={select => this.select = select}>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                    </select>&nbsp;
                    <button onClick={this.increment}>+</button>&nbsp;
                    <button onClick={this.decrement}>-</button>&nbsp;
                    <button onClick={this.incrementIfOdd}>increment if odd</button>&nbsp;
                    <button onClick={this.incrementAsync}>increment async</button>
                </div>
            </div>
        )
    }
}
