// react/react_app/src/components/search.jsx
import React, {Component} from 'react'

export default class Search extends Component {
    render () {
        return (
            <section className="jumbotron">
                <h3 className="jumbotron-heading">Search Github Users</h3>
                <div>
                    <input type="text" placeholder="enter the name you search"/>
                    <button>Search</button>
                </div>
            </section>
        )
    }
}

// vue/VueDemo/src_basic/components/Search.vue
<template>
    <section class="jumbotron">
        <h3 class="jumbotron-heading">Search Github Users</h3>
        <div>
          <input type="text" placeholder="enter the name you search" v-model="searchName">
          <button @click="search">Search</button>
        </div>
    </section>
</template>

<script>
    import PubSub from 'pubsub-js'

    export default {
      data () {
        return {
          searchName:''
        }
      },
      methods: {
        search () {
          const searchName = this.searchName.trim();
          if(searchName){
            PubSub.publish('search',searchName);
          }
        }
      }
    }
</script>

<style>

</style>
