// react/react_app/src_users/components/search.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'

export default class Search extends Component {

    static propTypes = {
        setSearchName: PropTypes.func.isRequired
    }

    search = () => {
        const searchName = this.input.value.trim()
        if (searchName) {
            this.props.setSearchName(searchName)
        }
    }

    render () {
        return (
            <section className="jumbotron">
                <h3 className="jumbotron-heading">Search Github Users</h3>
                <div>
                    <input type="text" placeholder="enter the name you search" ref={input => this.input =input} />
                    <button onClick={this.search}>Search</button>
                </div>
            </section>
        )
    }
}

// vue/VueDemo/src_basic/components/Search.vue
<template>
    <section class="jumbotron">
        <h3 class="jumbotron-heading">Search Github Users</h3>
        <div>
          <input type="text" placeholder="enter the name you search" v-model="searchName">
          <button @click="search">Search</button>
        </div>
    </section>
</template>

<script>
    import PubSub from 'pubsub-js'

    export default {
      data () {
        return {
          searchName:''
        }
      },
      methods: {
        search () {
          const searchName = this.searchName.trim();
          if(searchName){
            PubSub.publish('search',searchName);
          }
        }
      }
    }
</script>

<style>

</style>
